language: node_js
node_js:
- '4.2'
before_script:
- rvm install 2.2.3
- bundle install
script:
- npm run lint
- bundle exec rake test
sudo: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  slack:
    secure: MLjJFt1IlyxcsSo2KBHwFuE8U8pnDt2g6u2/AN0PdNi2xT1Y2IeG29RL4McfMJqtAyhbEw/029cOmzQPky6/87EHz+MB3p9TpGgXOLg0G0hdrrymHo6Xzlh/Mu8ayu6+c8Nl0/ctdKuv90kOBk3evJEqlO7P+I2uEJfE6FmsPUmynZPvH3lrBx01CRUVfh5UyxkWLrE78iEFEQqvEHKDB7cx0Rmc1uuaPIc51JH2T/sZ3PVdRTcjQjg6A8wMbX2LoAn3nACNSCsGGKiOa6FNSNsG+1TgwaffqfJegfYDtDDGB0kUXBigxlRh5lY9H4b05vbYeyzDfQm7aIUoeDIFR9TGJxWc311jmYUimbqF+A3c13q1IPzIVd9XBtgGtYGtXS9zISNckuK8pS7dObtJjlAYH19UkD+LgCeOyKF2oKlzGZ29WSgFrG18mTBnruL4105u1Hdc/HT2bXWdDIYhQSLKnIGHeIuxPLNCL/P0gknEeR8FRfxA95zjjlTTqyom/IkBaC7J5LGGaLN9z6DQkgQEUaAGY2ehY6SJ4tRCiOVsuBHCwfuNHJFAWSbTFfZEJzCetEFeRIbXa6hHmNAolXDjFuuSWLXbQnE+48i5AsHfCXAshBt+LBhZOUzZK5XMUYgQ5EHWwl8nsyI0c6+B5bjJxa+I14ynU5YIC18JbVg=
